### PR TITLE
Fix broken template example link.

### PR DESCRIPTION
**Pull request by MatthewWid**
| Q                | A
| ---------------- | ---
| Bug fix?         | no (?)
| New feature?     | no
| Breaking change? | no
| Deprecations?    | no
| Tests added?     | no
| Fixed issues     | 
| License          | Apache-2.0

The [original link](https://nhnent.github.io/tui.jsdoc-template/latest/) to the example of the "tui-jsdoc" template was incorrect and went to a 404 page - it has now been updated with [the correct link](https://nhn.github.io/tui.jsdoc-template/latest/).

### CODE REVIEW

**Comment by alexanderankin** [comment]
@didaquis please merge this i was about to submit another PR myself

**Comment by didaquis** [comment]
hi @alexanderankin, I don't have permissions on this repository

**Comment by alexanderankin** [comment]
@didaquis sorry my apologies.

**Comment by alexanderankin** [comment]
@hegemonic ?

**Pull request closed without merging**
