### PR TITLE
Makes title configurable.

### PR DESCRIPTION
**Pull request by ceving**

### CODE REVIEW

**Comment by jorgebay** [comment]
+1 It would be really nice to have, to avoid changing the template just for the title...

**Comment by lucidfox** [comment]
Any progress on merging this?

**Comment by BenjaminVanRyseghem** [comment]
@ceving ping?

**Comment by JoshuaCWebDeveloper** [comment]
It would be nice to see this merged in.

@PixEye It looks like that the syntax error you mentioned was fixed by the second commit: 4897005e

**Comment by crs1138** [comment]
It'd be awesome to get this PR merged after 4 years. What can I do to help?

**Comment by jonathancross** [comment]
@hegemonic Would you be able to merge this if it was rebased?

**Comment by jisotalo** [comment]
It would be nice to see this or #1570 merged after all these years

**Comment by mcandre** [comment]
People have completed entire college degrees before this tiny feature gets merged.

I say we fork jsdoc, so that we can develop it at a reasonable pace.

**Comment by lovasoa** [comment]
@hegemonic : You are the latest person to have committed to master. Maybe you can help getting this merged ?

**Comment by Alvarito050506** [comment]
It's 2021, and after 6 years this small (yet really useful) feature hasn't been merged... :confused:

**Comment by lovasoa** [comment]
I think this project simply isn't maintained anymore.

**Comment by jonathancross** [comment]
@hegemonic

**Pull request closed without merging**
