### PR TITLE
Update version of marked dependency

### PR DESCRIPTION
**Pull request by drazisil**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Deprecations?    | no
| Tests added?     | no
| Fixed issues     | comma-separated list of issues fixed by the pull request, if any
| License          | Apache-2.0

https://www.npmjs.com/advisories/812

There is a security issue with the version of `marked` in use. This PR addresses that

### CODE REVIEW

**Comment by collinwu** [comment]
last commit merged was on January 20. not sure this will get addressed anytime soon unfortunately :(

**Comment by drazisil** [comment]
Hi @hegemonic 

No rush, but when you get a chance can you take a look, please :)

**Comment by bizob2828** [comment]
@hegemonic any chance you could merge this? This vulnerability has been opened for several weeks now

**Comment by hegemonic** [comment]
Fixed in a separate commit. The fix will be included in JSDoc 3.6.0, which I'll be releasing very soon.

**Pull request closed without merging**
