### PR TITLE
Add typescript, attempt #2

### PR DESCRIPTION
**Pull request by sandersn**
Update of #1560; it is now only one line long.

### CODE REVIEW

**Comment by sandersn** [comment]
Tests fail because Typescript can parse more programs than other parsers. I made the test that was supposed to be unparseable even harder to parse, so that Typescript will also fail to parse it.

**Comment by lll000111** [comment]
Does this work around this TS Babel plugin issue? https://github.com/jsdoc3/jsdoc/issues/272#issuecomment-487312799
The TS Babel plugin accidentally removes JSDoc comments when (it thinks) they belong to the removed Typescript definition. Especially bad when it removes `@typedef` JSDoc comments.

**Comment by hegemonic** [comment]
I would very much like for JSDoc to support TypeScript, but it's not clear to me that just turning on TypeScript in `@babel/parser` is good enough. Does that actually result in useful documentation?

**Comment by lll000111** [comment]
@hegemonic I'm using it after switching all my .Flow using .js files to TS using.ts files (not that TS is better, but it's much more mainstream). Works just fine, apart from what I mention in the comment linked above. Which means the module links (don't work, as described, I had to hack the template because instead of `module:myModule.myFunction` I get `myModule.module:ts.myFunction`

**Comment by hegemonic** [comment]
@lll000111 You're running JSDoc against the JS files that Babel generates, not the TS files, right? If so, it makes sense to me that things would (sorta kinda almost) work.

The trouble is that when `@babel/parser` parses a TS file, it generates all sorts of AST nodes that aren't part of the [ESTree spec](https://github.com/estree/estree) (or at least it did the last time I checked; it seems like it would have to). JSDoc doesn't know anything about those TS-specific AST nodes. I don't think there's any quick and easy way to get JSDoc to recognize them, or to do something useful with them. And I don't want to claim that JSDoc supports TypeScript unless it can generate useful documentation for unmodified TypeScript files.

**Comment by lll000111** [comment]
> You're running JSDoc against the JS files that Babel generates, not the TS files, right?

@hegemonic No, against the .ts files.

**Pull request closed without merging**
